ARG DOCKER_NAMESPACE="balenalib"
ARG ARCHITECTURE="amd64"
ARG RESTY_IMAGE_BASE="alpine"
ARG RESTY_IMAGE_TAG="3"

FROM ${DOCKER_NAMESPACE}/${ARCHITECTURE}-${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

RUN ["cross-build-start"]

RUN install_packages \ 
        make \
        gcc \
        make \
        g++ \
        zlib-dev \
        musl-dev \
        pcre-dev \
        openssl-dev \
        zlib-dev \
        ncurses-dev \
        readline-dev \
        curl \
        perl \
        libffi-dev \
        git \
        unzip \
        tar \
        openssh \
        m4 \
        xz \
        gnupg \
        openssl \
        musl \
        linux-headers \
        bsd-compat-headers \
        bash \
        go \
        patch

RUN ["cross-build-end"]
